#!/bin/bash
min = 0
printf "\n\n===== updating github =====\n\n"
if [$# -ne $min]
then
	git add --all . && git commit -m "$1 $2"
	git push
else
	echo "Enter msg: "
	read msg
	git add --all . && git commit -m "$msg"
	git push
fi;
sleep 2
clear
